# Generated by Django 5.2.10 on 2026-01-13 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeltOptimizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('initial_chemistry', models.JSONField()),
                ('target_chemistry', models.JSONField()),
                ('melt_weight_kg', models.FloatField()),
                ('response_status', models.CharField(db_index=True, max_length=20)),
                ('response_data', models.JSONField()),
                ('processing_time_ms', models.FloatField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(default=200)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Melt Optimization Request',
                'verbose_name_plural': 'Melt Optimization Requests',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='meltopt_mel_timesta_e11116_idx'), models.Index(fields=['response_status'], name='meltopt_mel_respons_7eb982_idx')],
            },
        ),
    ]
